Algoritmo "Cap 3 Nº1.3"
// Disciplina   : Programação e Estrutura de Dados I
// Professor   : NARA MARTINI BIGOLIN
// Autor(a)    : CRISTIAN AUGUSTO SIMON
// Data atual  : 26/05/2021

Var
L,P,A,D:real
Inicio
escreval ("*****Calculador de AREA, PERIMETRO E DIAGONAL DE UM QUADRADO*****")
escreval ("Introduza a medida do lado")
Leia (L)
P<-(L*L)
A<-(L*4)
D<-(L*1.41421356237)
escreval ("Dados do quadrado: perimetro",P,", área",A," e diagonal",D,"!")
Fimalgoritmo