Algoritmo "Cap 3 Nº9"
// Disciplina   : Programação e Estrutura de Dados I
// Professor   : NARA MARTINI BIGOLIN
// Autor(a)    : CRISTIAN AUGUSTO SIMON
// Data atual  : 26/05/2021

Var
A,B,AUX:real
Inicio
escreval ("Invertendo valores")
escreval ("Insira o primeiro valor:")
Leia (A)
escreval ("Insira o segundo valor:")
Leia (B)
AUX<-(A)
A<-(B)
B<-(AUX)
escreval ("O primeiro valor é ",A," e o segundo valor é ",B,".")
Fimalgoritmo