Algoritmo "Cap 4 Nº1.2"
// Disciplina   : Programação e Estrutura de Dados I
// Professor   : NARA MARTINI BIGOLIN
// Autor(a)    : CRISTIAN AUGUSTO SIMON
// Data atual  : 06/06/2021
Var
N:real
Inicio
escreval ("****Calculador de Intervalo******")
escreval("Insira um número:")
Leia (N)
se (N<10) ou (N>=100) entao
escreval("O número ",N," não está no intervalo de 10 a 99")
senao
escreval("O número ",N," está no intervalo de 10 a 99")
fimse
Fimalgoritmo