Algoritmo "Cap 3 Nº15"
// Disciplina   : Programação e Estrutura de Dados I
// Professor   : NARA MARTINI BIGOLIN
// Autor(a)    : CRISTIAN AUGUSTO SIMON
// Data atual  : 26/05/2021

Var
VAL,V,VE,VP:real
Inicio
escreval ("*****Calculador de Custo de Veículo*****")

escreval ("Insira o valor da compra:")
Leia (VAL)
V<-(VAL/5)
VE<-(V*3)
VP<-(V)
escreval ("O valor de entrada é ",VE,"  e mais duas parcelas de ",VP," reais!")
Fimalgoritmo